stages:
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip"

prepare:
  stage: build
  script:
    - module load Python/2.7.15-foss-2018b
    - ./bootstrap.sh
    - source python_env/bin/activate
    - pip install sphinx sphinx_rtd_theme
    - module load Python/3.6.6-foss-2018b
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install pyaml
  cache:
    paths:
      - python_env
      - venv
      - pip
  artifacts:
    paths:
      - python_env
      - venv
    expire_in: 24 hours


steptests:
  stage: test
  script:
    - module load Python/3.6.6-foss-2018b
    - source venv/bin/activate
    - git clone git@ribogit.izi.fraunhofer.de:oneButton/uap_test.git
    - cd uap_test
    - make clean
    - python3 scripts/uap_test.py run-tests --uap-test-dir . --uap-path ../uap
  cache:
    paths:
      - uap_test
  dependencies:
    - prepare

pages:
  stage: test
  script:
    - module load Python/2.7.15-foss-2018b
    - source python_env/bin/activate
    - sphinx-build -b html doc/source public
  dependencies:
    - prepare
  artifacts:
    paths:
    - public
  only:
  - 117-docu-not-online

