#before_script:
#  - eval $(ssh-agent -s)

stages:
  - build
  - test
  
  
.dummy:
  stage: build
  script:
    - pwd
    - ls ~/.ssh/*
    - git clone git@ribogit.izi.fraunhofer.de:oneButton/uap_test.git
    

prepare:
  stage: build
  script:
    - pwd
    - ./bootstrap.sh
    
  artifacts:
    paths:
      - python_env
    expire_in: 24 hours



steptests:
  stage: test
  script:
    - git clone git@ribogit.izi.fraunhofer.de:oneButton/uap_test.git 
    - pwd
    - cd  uap_test
    - make clean
    - module load Python/3.6.3-foss-2016b
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install pyaml
    - python3 scripts/uap_test.py --uap-test-dir . --uap-path ../uap 
  dependencies:
    - prepare


#    -



                

