stages:
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip"
  GIT_SUBMODULE_STRATEGY: recursive

prepare:
  stage: build
  script:
    - module load Python/2.7.15-foss-2018b
    - ./bootstrap.sh
    - source python_env/bin/activate
    - python -m pip install sphinx sphinx_rtd_theme
    - deactivate
    - module load Python/3.6.6-foss-2018b
    - python3 -m venv venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip
    - python -m pip install pyyaml
  cache:
    key: python-envs
    paths:
      - python_env
      - venv
      - pip
  artifacts:
    paths:
      - python_env
      - venv
    expire_in: 24 hours


steptests:
  stage: test
  script:
    - module load Python/3.6.6-foss-2018b
    - source venv/bin/activate
    - cd uap_test
    - python3 scripts/uap_test.py run-tests --uap-test-dir . --uap-path ../uap
  dependencies:
    - prepare

pages:
  stage: test
  script:
    - module load Python/2.7.15-foss-2018b
    - source python_env/bin/activate
    - rm -r public/$CI_COMMIT_REF_SLUG || echo "First doc for $CI_COMMIT_REF_SLUG"
    - sphinx-build -b html doc/source public/$CI_COMMIT_REF_SLUG
    - cp -r doc/supp public
    - rm -r piblic/supp public/fav
    - doc/make_pages_index.sh public
  cache:
    key: pages-cache
    paths:
      - public
  dependencies:
    - prepare
  artifacts:
    paths:
    - public
