stages:
  - build
  - test

steptests:
  stage: test
  script:
    - pwd
    - cd  /mnt/fhgfs_ribdata/uap_test
    - make clean
#    - python3 /homes/olymp/sven-holger.puppel/playground/run_uap_test.py --uap-test-dir /mnt/fhgfs_ribdata/uap_test


