before_script:
    - eval $(ssh-agent -s)

stages:
  - build
  - test
  
  
dummy:
  stage: build
  script:
    - pwd
    - ls ~/.ssh *
    - git clone clone git@ribogit.izi.fraunhofer.de:oneButton/uap_test.git
    

.prepare:
  stage: build
  script:
    - pwd
    - ./bootstrap.sh
    
  artifacts:
    paths:
      - python_env
    expire_in: 24 hours



.steptests:
  stage: test
  script:
    - git clone git@ribogit.izi.fraunhofer.de:oneButton/uap_test.git 
    - pwd
    - cd  uap_test
    - make clean
    - python3 scripts/run_uap_test.py --uap-test-dir . --uap-path ../uap 
  dependencies:
    - prepare


#    -



                

