stages:
  - test_and_deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip"

cache:
  paths:
    - python_env
    - venv
    - pip
    - uap_test

before_script:
  - module load Python/2.7.15-foss-2018b
  - ./bootstrap.sh
  - module load Python/3.6.6-foss-2018b
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install pyaml sphinx


steptests:
  stage: test_and_deploy
  script:
    - git clone git@ribogit.izi.fraunhofer.de:oneButton/uap_test.git
    - cd uap_test
    - make clean
    - module load Python/3.6.6-foss-2018b
    - source venv/bin/activate
    - python3 scripts/uap_test.py run-tests --uap-test-dir . --uap-path ../uap
  dependencies:
    - prepare

pages:
  stage: test_and_deploy
  script:
    - module load Python/3.6.6-foss-2018b
    - source venv/bin/activate
    - sphinx-build -b html doc/source public
  dependencies:
    - prepare
  artifacts:
    paths:
    - public
  only:
  - 117-docu-not-online

